#!/usr/bin/env bash
# using loops to iterate

i=0;

while [[ $i -lt 10 ]]; do
	i=$((i + 1))
	if [[ $i -eq 4 ]]; then
		echo "bad luck"
		continue;

	elif [[ $i -eq 8 ]]; then
		echo "good luck"
		continue;
	else
		echo "Best School"
	fi
done
