#!/usr/bin/env bash
#using if to check for file presence and size

FILE="school"

if [[ -e $FILE ]]; then

	echo "school file exists"
	
	if [[ -s $FILE ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [[ -f $FILE ]]; then

		echo "school is a regular file"
	else 
		#do nothing for non regular file
		:
	fi


else 
	echo "school file does not exist"

fi
