#!/usr/bin/env bash
#using while to make a story

while read -r line; do
	
#assigning variables to use in the story

	username="$(echo "$line" | cut -d':' -f1)"
	passwd="$(echo "$line" | cut -d':' -f2)"
	userid="$(echo "$line" | cut -d':' -f3)"
	groupid="$(echo "$line" | cut -d':' -f4)"
	userinfo="$(echo "$line" | cut -d':' -f5)"
	home="$(echo "$line" | cut -d':' -f6)"
	shell="$(echo "$line" | cut -d':' -f7)"

	echo "text".


done
